# Importamos bibliotecas (o librerías, qué sé yo...)

In [1]:
import numpy as np

---
# Ingredientes esenciales para método iterativos
### 🤓 Oye profesore cerebrón, corre ya de una vez todo el código que sigue y dime qué da... (https://www.youtube.com/watch?v=rPsMIZrJSWU)
---

## Defino una matriz ¡Correme!

In [2]:
matriz = np.array([ [1,2,3], [-2,8,5] , [10,2,30] ]) #se define por filas
print(matriz)

[[ 1  2  3]
 [-2  8  5]
 [10  2 30]]


## ¡Dame la inversa de una matriz ya! ¡Correme!
### 📤 Bueno, pero no se enoje... https://www.youtube.com/watch?v=jmzNApFzXhY

In [3]:
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[ 1.16161616e+00 -2.72727273e-01 -7.07070707e-02]
 [ 5.55555556e-01  2.64338815e-17 -5.55555556e-02]
 [-4.24242424e-01  9.09090909e-02  6.06060606e-02]]


## Le quiero extraer la diagonal a una matriz ¡Correme!

In [4]:
vector_diagonal = np.diag(matriz)
print(vector_diagonal)

[ 1  8 30]


## Quiero una matriz diagonal con ese vector ¡Correme!
### (⚽ Sí, muchas diagonales, como las que tiraba Claudio Paul (bueno, no es una diagonal, pero usted me entiende la idea) https://www.youtube.com/watch?v=y3einh1kTMg&pp=ygURY2FuaWdnaWEgZGlhZ29uYWw%3D)

In [5]:
vector_en_la_diagonal = np.array([10,-3,4,0.13])
matriz_diagonal = np.diag(vector_en_la_diagonal)
print(matriz_diagonal)

[[10.    0.    0.    0.  ]
 [ 0.   -3.    0.    0.  ]
 [ 0.    0.    4.    0.  ]
 [ 0.    0.    0.    0.13]]


## Quiero extraer la parte triangular superior (estrictamente) ¡Correme!

In [6]:
matriz_superior_estricta = np.triu(matriz,1)
print(matriz_superior_estricta)

[[0 2 3]
 [0 0 5]
 [0 0 0]]


## Quiero extraer la parte triangular inferior (estrictamente) ¡Correme!

In [7]:
matriz_superior_estricta = np.tril(matriz,-1)
print(matriz_superior_estricta)

[[ 0  0  0]
 [-2  0  0]
 [10  2  0]]


## ¿Y una matriz con ...? Bueno ya, lee la @##%#^$%^ 🗯 documentación de una vez
### https://numpy.org/doc/stable/reference/routines.array-creation.html#building-matrices
### https://numpy.org/doc/stable/reference/routines.linalg.html

---
---
## **Ahora sí, a por el ejercicio 1 de la práctica 5: codear Gauss-Seidel y Jacobi (con alguna cosilla más). ¡Perfectirijillo!**

### 🧒 Codear Jacobi y Gauss-Seidel: escucha a tu niñe interior, la comida va aquí . https://www.youtube.com/watch?v=QMKRrWMl8s0


In [8]:
# Tu código va aquí.




## ¡Ponga a prueba su código! (algún ejercicio de la práctica, o lo que usted desee).
### 🌗 Pase alguna vez por esa experiencia cósmica, https://www.youtube.com/watch?v=XKVDB46VQWQ

In [9]:
# Ponga a prueba su código aquí.




---
### ✅ Oh pequeñe saltamontes, ¿anda usted con problemillas de programación? ¡Pues no se resista a que el patito venga en su ayuda! https://rubberduckdebugging.com/

---
---
## ✋ ¿Y a Seidel quién lo juna?
### Cuenta la leyenda (léase, es cierto) que don Philipp Ludwig von Seidel, leyendo una demostración de Cauchy, le encontró un pifie y, a partir de intentar arreglarlo, ¡inventó el concepto de convergencia uniforme! (avise si se va a desmayar luego de tamaña noticia...).
### También es culpable de las 5 aberraciones de Seidel (pero aberraciones en el sentido buena onda): https://en.wikipedia.org/wiki/Optical_telescope#The_five_Seidel_aberrations

---

## ✋ Bueno dale, decí algo de Gauss, que al fin y al cabo es el famoso
### Dedekind fue estudiante de Gauss: https://www.mathgenealogy.org/id.php?id=18233

---

### ✋ Y de yapa, ya que mencionamos al queridísimo Augustin-Louis Cauchy, ¿usted sabía que tiene su nombre tallado en la mismísima torre Eiffel? ¡Ja! Bueno, junto a otros 71, pero igual le damos crédito parcial: https://en.wikipedia.org/wiki/List_of_the_72_names_on_the_Eiffel_Tower