# Importamos bibliotecas (o librerías, qué sé yo...)

In [1]:
import numpy as np

---
# Ingredientes esenciales para método iterativos

---

## Defino una matriz ¡Correme!

In [ ]:
matriz = np.array([ [1,2,3], [-2,8,5] , [1,2,30] ]) #se define por filas
print(matriz)

[[ 1  2  3]
 [-2  8  5]
 [ 1  2 30]]


## ¡Dame la inversa de una matriz ya! ¡Correme!
### 📤 Bueno, pero no se enoje... https://www.youtube.com/watch?v=jmzNApFzXhY

In [5]:
matriz_inversa = np.linalg.inv(matriz)
print(matriz_inversa)

[[ 0.70987654 -0.16666667 -0.04320988]
 [ 0.20061728  0.08333333 -0.03395062]
 [-0.03703704  0.          0.03703704]]


## Le quiero extraer la diagonal a una matriz ¡Correme!

In [6]:
vector_diagonal = np.diag(matriz)
print(vector_diagonal)

[ 1  8 30]


## Quiero una matriz diagonal con ese vector ¡Correme!
### (⚽ Sí, muchas diagonales, como las que tiraba Claudio Paul (bueno, no es una diagonal, pero usted me entiende la idea) https://www.youtube.com/watch?v=y3einh1kTMg&pp=ygURY2FuaWdnaWEgZGlhZ29uYWw%3D)

In [7]:
vector_en_la_diagonal = np.array([10,-3,4,0.13])
matriz_diagonal = np.diag(vector_en_la_diagonal)
print(matriz_diagonal)

[[10.    0.    0.    0.  ]
 [ 0.   -3.    0.    0.  ]
 [ 0.    0.    4.    0.  ]
 [ 0.    0.    0.    0.13]]


## Quiero extraer la parte triangular superior (estrictamente) ¡Correme!

In [8]:
matriz_superior_estricta = np.triu(matriz,1)
print(matriz_superior_estricta)

[[0 2 3]
 [0 0 5]
 [0 0 0]]


## Quiero extraer la parte triangular inferior (estrictamente) ¡Correme!

In [9]:
matriz_superior_estricta = np.tril(matriz,-1)
print(matriz_superior_estricta)

[[ 0  0  0]
 [-2  0  0]
 [ 1  2  0]]


## ¿Y una matriz con ...? Bueno ya, lee la @##%#^$%^ 🗯 documentación de una vez
### https://numpy.org/doc/stable/reference/routines.array-creation.html#building-matrices
### https://numpy.org/doc/stable/reference/routines.linalg.html

---
---
## **Ahora sí, a por el ejercicio 1 de la práctica 5: codear Gauss-Seidel y Jacobi (con alguna cosilla más). 




In [44]:
matriz = np.array([ [1,2,30], [20,8,5] , [1,2,30] ])
b =  np.array([2,3,3])
x = np.array([1,3,0])


def  es_diag_dom(A):
    for i in range(len(A)):
        if A[i,i] > np.sum(A[i]) - A[i,i]:
            x = True
        else:
            return False
    return True



In [ ]:
# Tu código va aquí.
matriz = np.array([ [10,2,3], [20,8,5] , [1,2,30] ])
b =  np.array([2,3,3])
x = np.array([1,3,0])


def  es_diag_dom(A):
    for i in range(len(A)):
        if np.abs(A[i,i]) > np.abs(np.sum(A[i]) - A[i,i]):
            x = True
        else:
            return False
    return x 



def metodo_jacobi(A, b, x, N):
    if es_diag_dom(A):
     L = np.tril(A,-1)
     U = np.triu(A,1)
     D = np.diag(np.diag(A))

     B_j =  - np.linalg.inv(D) @ (L + U)
     C_j = np.linalg.inv(D) @ b
     for i in range(N):
         x_sig = B_j @ x + C_j
         x = x_sig
     return x
    
    else:
       print("La convergencia no está garantizada.")
       L = np.tril(A,-1)
       U = np.triu(A,1)
       D = np.diag(np.diag(A))
  
       B_j =  - np.linalg.inv(D) @ (L + U)
       C_j = np.linalg.inv(D) @ b

       for i in range(N):
           x_sig = B_j @ x + C_j
           error = np.linalg.norm(x_sig - x) / np.linalg.norm(x_sig)
           x = x_sig

           if error < 1e-10:
               print(f"Convergencia alcanzada en {i+1} iteraciones")
               break
           
       return x



metodo_jacobi(matriz, b, x, 70)


La convergencia no está garantizada.


array([ 0.21227202, -0.22305127,  0.10779438])

In [69]:
import numpy as np

def es_diag_dom(A):
    """
    Verifica si una matriz es estrictamente diagonal dominante
    """
    n = A.shape[0]
    for i in range(n):
        suma_fuera_diagonal = np.sum(np.abs(A[i])) - np.abs(A[i,i])
        if np.abs(A[i,i]) <= suma_fuera_diagonal:
            return False
    return True

def metodo_jacobi(A, b, x0, N):
    """
    Implementa el método de Jacobi
    """
    n = A.shape[0]
    
    # Verificar si A es diagonal dominante (condición suficiente para convergencia)
    if not es_diag_dom(A):
        print("Advertencia: La matriz no es estrictamente diagonal dominante.")
        print("La convergencia no está garantizada.")
    
    # Extraer componentes
    D = np.diag(np.diag(A))  # Matriz diagonal
    L_plus_U = A - D         # L + U
    
    # Matriz de iteración de Jacobi
    D_inv = np.linalg.inv(D)
    T_j = -D_inv @ L_plus_U  # Matriz de iteración
    c_j = D_inv @ b          # Vector constante
    
    # Verificar radio espectral (condición necesaria y suficiente)
    radio_espectral = np.max(np.abs(np.linalg.eigvals(T_j)))
    print(f"Radio espectral de T_j: {radio_espectral:.6f}")
    
    if radio_espectral >= 1:
        print("¡ADVERTENCIA! Radio espectral >= 1. El método puede divergir.")
        return None
    
    # Iteraciones de Jacobi
    x = x0.copy()
    for i in range(N):
        x_new = T_j @ x + c_j
        # Calcular error relativo
        error = np.linalg.norm(x_new - x) / np.linalg.norm(x_new)
        if i % 10 == 0:  # Mostrar progreso cada 10 iteraciones
            print(f"Iteración {i}: error = {error:.2e}")
        x = x_new
        
        # Criterio de parada opcional
        if error < 1e-10:
            print(f"Convergencia alcanzada en {i+1} iteraciones")
            break
    
    return x

# --- PRUEBA ---
# Tu matriz de ejemplo (CORREGIDA - la original tenía filas repetidas)
matriz = np.array([ 
    [10, 2, 1],    # Cambiado para hacerla diagonal dominante
    [1, 8, 2], 
    [1, 1, 12] 
])

b = np.array([2, 3, 3])
x0 = np.array([1, 3, 0])

print("Matriz A:")
print(matriz)
print(f"\n¿Es diagonal dominante? {es_diag_dom(matriz)}")

solucion = metodo_jacobi(matriz, b, x0, 50)

if solucion is not None:
    print(f"\nSolución aproximada: {solucion}")
    print(f"Residuo: {np.linalg.norm(matriz @ solucion - b):.2e}")
    
    # Comparar con solución exacta
    sol_exacta = np.linalg.solve(matriz, b)
    print(f"Solución exacta: {sol_exacta}")
    print(f"Error: {np.linalg.norm(solucion - sol_exacta):.2e}")

Matriz A:
[[10  2  1]
 [ 1  8  2]
 [ 1  1 12]]

¿Es diagonal dominante? True
Radio espectral de T_j: 0.270910
Iteración 0: error = 6.44e+00
Iteración 10: error = 1.30e-05
Iteración 20: error = 2.76e-11
Convergencia alcanzada en 21 iteraciones

Solución aproximada: [0.11719606 0.30668127 0.21467689]
Residuo: 2.80e-11
Solución exacta: [0.11719606 0.30668127 0.21467689]
Error: 2.31e-12


In [25]:

def metodo_gauss_seidel(A, b, x, N):
    L = np.tril(A,-1)
    U = np.triu(A,1)
    vector_diagonal = np.diag(A)
    D = np.diag(vector_diagonal)

    B_j =  - np.linalg.inv(L+D) @  U 

    C_j = np.linalg.inv(L+D) @ b


    for i in range(N):
        x_sig = B_j @ x + C_j
        x = x_sig
    return x

metodo_gauss_seidel(matriz, b, x, 50)

array([0.11829945, 0.35951941, 0.07208872])

In [26]:
def  es_diag_dom(A):
    for i in range(len(A)):
        if A[i,i] > np.sum(A[i]) - A[i,i]:
            x = True
        else:
            return False
    return True